name: Build and Publish the Desktop App

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use for release'     
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Publish and Publish the Desktop App for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            artifact_path: bundle/deb/discourse_${{ github.event.inputs.version }}_amd64.AppImage
            asset_name: Discourse.AppImage
          - os: windows-latest
            artifact_path: bundle/msi/Discourse_${{ github.event.inputs.version }}_x64.msi
            asset_name: Discourse.msi
          - os: macos-latest
            artifact_path: cbundle/dmg/Discourse_${{ github.event.inputs.version }}_x64.dmg
            asset_name: Discourse.dmg
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Tauri CLI
      - run: cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch next
      - name: Build
        run: cargo tauri build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./src-tauri/target/release/${{ matrix.artifact_path }}
          tag: discourse-${{ github.event.inputs.version }}
          asset_name: ${{ matrix.asset_name }}
          release_name: Discourse ${{ github.event.inputs.version }}
